FROM rockylinux:8-minimal
ENV container=docker

# MITRE SSL Fun
RUN curl -ksSL \
    https://gitlab.mitre.org/mitre-scripts/mitre-pki/raw/master/os_scripts/install_certs.sh \
    | MODE=centos sh

RUN microdnf -y install epel-release
RUN microdnf --enablerepo=powertools install -y netcdf-devel netcdf-cxx redhat-lsb libaec eccodes 
RUN microdnf --enablerepo=devel install eccodes-devel
