# You can control the aaesim branch/tag in this container from the command line, like this:
# >> docker build -t aaesim:4.0.0 --build-arg ARG_AAESIM_GIT_TAG=v4.0.0 -f Dockerfile.deploy_v4 .
FROM artifacts.mitre.org:8200/idealab/rocky/idealab-basic:2.0.0 AS build
ENV container docker

# Install Run Dependencies
# BADA data (needed by AAESim/FMACM in order to run a scenario)
RUN mkdir /data \
    && mkdir /data/aaesim \
    && mkdir /data/aaesim/regressionScens \
    && git clone -b master --depth 1 https://mustache.mitre.org/scm/aaes/bada-data.git /data/aaesim/regressionScens/bada

# Install AAESim code
ARG ARG_AAESIM_GIT_TAG='main'
ENV AAESIM_VERSION=$ARG_AAESIM_GIT_TAG
USER demo
RUN cd /home/demo \
    && git clone --branch ${AAESIM_VERSION} --depth 1 https://mustache.mitre.org/scm/aaes/aaesim.git aaesim

# System must have a "cmake3" for aaesim builds
USER root
RUN ln -s /usr/local/bin/cmake /usr/local/bin/cmake3

# Build aaesim
USER demo
RUN cd /home/demo/aaesim \
    && cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release \
    && cmake --build build --target aaesim FMACM

# Begin Testing --------------------------

# Install Test Data Dependencies
# NOTE: this container is ~7GB! You only need it if you intend to run aaesim unit/regression tests inside the container
# USER root
# COPY --from=artifacts.mitre.org:8200/docker/sbowman/aaesim_regression_data:latest /data/aaesim/regression_input_data /data/aaesim/regression_input_data

# Unit Test
# USER demo
# RUN cd /home/demo/aaesim/build \
#     && make run

# Regression Test
# NOTE: complete regression testing can run for a long time. Only use the "mini" test target to expedite this last step
# RUN cd /home/demo/aaesim/regression \
#     && make mini

# End Testing --------------------------

# ---
# Buildinfo Example: docker run --rm -it aaesim:<tag>
# Run Local Config Example: docker run --rm -it -v `pwd`:`pwd` -w `pwd` aaesim:<tag> <config-file>
FROM artifacts.mitre.org:8200/aaesim/aaesim-minimal:2.2.0
ENV container docker
COPY --from=build /data/aaesim/regressionScens/bada /data/aaesim/regressionScens/bada
COPY --from=build /home/demo/aaesim/bin/aaesim /home/demo/aaesim/bin/aaesim
COPY --from=build /home/demo/aaesim/build/_deps/caasdwind-src/local /home/demo/aaesim/build/_deps/caasdwind-src/local
ENTRYPOINT ["/home/demo/aaesim/bin/aaesim"]
CMD ["--buildinfo"]