# You can control the aaesim branch/tag in this container from the command line, like this:
# >> docker build -t aaesim:5.0.0 --build-arg ARG_AAESIM_GIT_TAG=v5.0.0 -f Dockerfile.deploy_v5 .
FROM --platform=$BUILDPLATFORM artifacts.mitre.org:8200/idealab/rocky/idealab-basic:3.0.1 AS build
ENV container=docker

RUN dnf --enablerepo=powertools install -y netcdf-devel netcdf-cxx libaec eccodes 
RUN dnf --enablerepo=devel install -y eccodes-devel

# Install Run Dependencies
# BADA data (needed by AAESim/FMACM in order to run a scenario)
RUN mkdir -p /data/aaesim/regressionScens \
    && git clone -b master --depth 1 https://mustache.mitre.org/scm/aaes/bada-data.git /data/aaesim/regressionScens/bada

# Install AAESim code
ARG ARG_AAESIM_GIT_TAG='v5.0.1'
ENV AAESIM_VERSION=$ARG_AAESIM_GIT_TAG
USER demo
RUN cd /home/demo \
    && git clone --branch ${AAESIM_VERSION} --depth 1 https://mustache.mitre.org/scm/aaes/aaesim.git aaesim_code

# System must have a "cmake3" for aaesim builds
USER root
RUN ln -s /usr/local/bin/cmake /usr/local/bin/cmake3

# Build aaesim
USER demo
RUN cd /home/demo/aaesim_code \
    && cmake3 -S. -Bbuild -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=FALSE -DBUILD_TESTING=FALSE\
    && cmake3 --build build --target FMACM aaesim

# ---
# Buildinfo Example: docker run --rm -it aaesim:<tag>
# Run Local Config Example: docker run --rm -it -v `pwd`:`pwd` -w `pwd` aaesim:<tag> <config-file>
FROM --platform=$BUILDPLATFORM artifacts.mitre.org:8200/aaesim/aaesim-minimal:2.3.0
ENV container=docker
COPY --from=build /data/aaesim/regressionScens/bada /data/aaesim/regressionScens/bada
COPY --from=build /home/demo/aaesim_code/bin/aaesim /home/demo/aaesim_code/bin/aaesim
ENTRYPOINT ["/home/demo/aaesim_code/bin/aaesim"]
CMD ["--buildinfo"]