//  THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESSED OR IMPLIED WARRANTIES,
//  INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
//  FITNESS  FOR A PARTICULAR  PURPOSE ARE  DISCLAIMED.  IN NO  EVENT SHALL  THE
//  APACHE SOFTWARE  FOUNDATION  OR ITS CONTRIBUTORS  BE LIABLE FOR  ANY DIRECT,
//  INDIRECT, INCIDENTAL, SPECIAL,  EXEMPLARY, OR CONSEQUENTIAL  DAMAGES (INCLU-
//  DING, BUT NOT LIMITED TO, PROCUREMENT  OF SUBSTITUTE GOODS OR SERVICES; LOSS
//  OF USE, DATA, OR  PROFITS; OR BUSINESS  INTERRUPTION)  HOWEVER CAUSED AND ON
//  ANY  THEORY OF LIABILITY,  WHETHER  IN CONTRACT,  STRICT LIABILITY,  OR TORT
//  (INCLUDING  NEGLIGENCE OR  OTHERWISE) ARISING IN  ANY WAY OUT OF THE  USE OF
//  THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#if !defined(aaesim_CPPMANIFEST_BUILDINFO_H)
#define aaesim_CPPMANIFEST_BUILDINFO_H

#if defined(aaesim_CPPMANIFEST_HAVE_PRAGMA_ONCE)
#pragma once
#endif

#include <iostream>
#include <string>

#define CPPMANIFEST_MAKE_STR(input) #input

// if suffix is empty, this will end with a hyphen. That will be removed at run-time
#define CPPMANIFEST_MAKE_VERSION_STR(major, minor, point, suffix) #major "." #minor "." #point "-" #suffix

//! This is CPPMANIFEST user name as a string.
#define aaesim_CPPMANIFEST_USERNAME_STR CPPMANIFEST_MAKE_STR(sbowman)

//! This is the build timestamp
#define aaesim_CPPMANIFEST_BUILDTIMESTAMP_STR CPPMANIFEST_MAKE_STR(2025 / 10 / 29 - 12 : 47 : 21)

//! This is the gcc version
#define aaesim_CPPMANIFEST_BUILD_C_VERSION_STR CPPMANIFEST_MAKE_STR(17.0.0.17000319)
#define aaesim_CPPMANIFEST_BUILD_CXX_VERSION_STR CPPMANIFEST_MAKE_STR(17.0.0.17000319)

//! Build system info
#define aaesim_CPPMANIFEST_BUILDSYSTEMNAME_STR CPPMANIFEST_MAKE_STR(Darwin)
#define aaesim_CPPMANIFEST_BUILDSYSTEMVERSION_STR CPPMANIFEST_MAKE_STR(24.6.0)
#define aaesim_CPPMANIFEST_BUILDSYSTEMPROCESSOR_STR CPPMANIFEST_MAKE_STR(arm64)
#define aaesim_CPPMANIFEST_BUILDHOSTNAME_STR CPPMANIFEST_MAKE_STR(MM292068 - PC)

//! Git SCM info
#define aaesim_CPPMANIFEST_GIT_BRANCH CPPMANIFEST_MAKE_STR(refs / heads / feat / update - to - v5.2.0)
#define aaesim_CPPMANIFEST_GIT_HASH CPPMANIFEST_MAKE_STR(17478c485d0241c046f655f55bb3f4ce8aad5155)
#define aaesim_CPPMANIFEST_GIT_TAG CPPMANIFEST_MAKE_STR()
#define aaesim_CPPMANIFEST_GIT_LOCAL_CHANGES CPPMANIFEST_MAKE_STR(CLEAN)

//! This is CPPMANIFEST version number as a string.
//! Do not wrap the suffix in quotes, but it may be left empty for a release
#define aaesim_CPPMANIFEST_VERSION_STR CPPMANIFEST_MAKE_VERSION_STR(5, 2, 0, 0)

#endif
